### ISSUE TITLE
Home customiser not working 

### ISSUE THREAD

**Issue by fastcolors** [fastcolors/skin.sio2#95]
@iCanuck

seems that id 211 doesn't get populated.. might be a Python issue. I tried changing Panel Id and adding

special://skin/playlists/random_movies.xsp in content, and the panel gets populated...

i'd say I wait for a fix at a lower level.

**Comment by fastcolors** [comment]
as you can see the list populates (of course won't work like this)... so it's a skin.shortcut vs leia issue, not at skin level

**Comment by fastcolors** [comment]
ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'NoneType' object has no attribute 'startswith'
                                            Traceback (most recent call last):
                                              File "/Users/macbook/Library/Application Support/Kodi/addons/script.skinshortcuts/resources/lib/gui.py", line 134, in onInit
                                                self.load_shortcuts()
                                              File "/Users/macbook/Library/Application Support/Kodi/addons/script.skinshortcuts/resources/lib/gui.py", line 272, in load_shortcuts
                                                item = self._parse_shortcut( shortcut )
                                              File "/Users/macbook/Library/Application Support/Kodi/addons/script.skinshortcuts/resources/lib/gui.py", line 399, in _parse_shortcut
                                                self._add_additional_properties( listitem )
                                              File "/Users/macbook/Library/Application Support/Kodi/addons/script.skinshortcuts/resources/lib/gui.py", line 424, in _add_additional_properties
                                                if customProperty[1].startswith("$") and not customProperty[ 1 ].startswith( "$SKIN" ):
                                            AttributeError: 'NoneType' object has no attribute 'startswith'
                                            -->End of Python script error report<--
23:30:18.719 T:140736285254464   ERROR: Control 211 in window 13006 has been asked to focus, but it can't

**Comment by iCanuck** [comment]
Okay good to know. I'll see if I can fix skinshortcuts or at least find a workaround for now.
